### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rodrigomelo9** [rodrigomelo9/zynq-examples#5]
Sorry, but there isn't a roadmap. Instead, I post here a list of things that I would like to include someday.

# Examples

- [ ] AXI DMA - polling
  - [x]  Zybo
  - [ ]  ZCU102
- [ ] AXI DMA - interrupts
  - [x]  Zybo
  - [ ]  ZCU102
- [ ] AXI DMA - scatter-gather
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS DMA
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS UART
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS I2C
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS SPI
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS CAN
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PS GEthernet
  - [ ]  Zybo
  - [ ]  ZCU102
- [ ] PL Transceivers
  - [ ]  ZCU102

# Documentation

- [x] Architecture - Zynq-7000
- [x] Architecture - Zynq-UltraScale+
- [ ] Vivado basic workflow
- [ ] PS alone
- [ ] PL alone (include how to store in QSPI/SD)
- [ ] How to perform a simulation
- [ ] How to use ILA

**Comment by rodrigomelo9** [comment]
Resources:
* https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/64488613/Using+the+JTAG+to+AXI+to+test+Peripherals+in+Zynq+Ultrascale
* https://github.com/Xilinx/embeddedsw
